In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing
df = pd.read_csv("C:/Users/miguel.postigo/Desktop/carpeta/programacion/python/kaggle/Pokemon.csv")
#[]

In [2]:
#rank 1; length axis 3
[1,2,3]

[1, 2, 3]

In [3]:
#rank 2; length axis 3
[[ 1, 2, 3],[ 4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

In [4]:
#create an array of NumPy through the array function
a = np.array([1, 2, 3])
b = np.array([(1,2,3), (4,5,6)])

print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [5]:
# a = np.array(1,2,3,4) # WRONG!!!

NumPy's array class is ndarray, which has an alias numpy.array, but it's different from array.array in the Python standard library
The latter is just a one-dimensional array

In [6]:
type(a)

numpy.ndarray

- *ndarray.ndim*: the dimension number of the array. It's called rank in Python.

- *ndarray.shape*: the dimension of the array. It's a series of numbers whose length is determined by the dimension （ndim） of the array. For example, the shape of a one-dimensional array with length n is n. And the shape of an array with n rows and m columns is n,m.

- *ndarray.size*: the number of all elements in the array.

- *ndarray.dtype*: the type of the element in the array, such as numpy.int32, numpy.int16, or numpy.float64.

- *ndarray.itemsize*: the size of each element in the array, in bytes.

- *ndarray.data*: the buffering for storing the array elements. Usually we only need to access the elements by subscripts, and don't need to access the buffer.

In [7]:
#nº de dimensiones del array/rank
print(a.ndim)
print(b.ndim)

1
2


In [8]:
#
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [9]:
a = np.array([1, 2, 3])
b = np.array([(1,2,3), (4,5,6)])

print('a=')
print(a)
#Nº DE DIMENSIONES del array/rank
print("a's ndim {}".format(a.ndim))
#la DIMENSION del array
print("a's shape {}".format(a.shape))
#Nº DE ELEMENTOS del array
print("a's size {}".format(a.size))
#TIPO de los elementos del array
print("a's dtype {}".format(a.dtype))
#TAMAÑO de cada elemento del array en bytes
print("a's itemsize {}".format(a.itemsize))

print('')

print('b=')
print(b)
print("b's ndim {}".format(b.ndim))
print("b's shape {}".format(b.shape))
print("b's size {}".format(b.size))
print("b's dtype {}".format(b.dtype))
print("b's itemsize {}".format(b.itemsize))

a=
[1 2 3]
a's ndim 1
a's shape (3,)
a's size 3
a's dtype int32
a's itemsize 4

b=
[[1 2 3]
 [4 5 6]]
b's ndim 2
b's shape (2, 3)
b's size 6
b's dtype int32
b's itemsize 4


We can also *specify the type of the element* when creating the array, for example:

In [10]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

# Create a specific array

- zeros: used to create an array whose elements are all 0

- ones: used to create an array whose elements are all 1

- empty: used to create uninitialized data. so the content is 
undefined.

- arange: used to create an array by specifying the scope and step-length (alcance y longitud de paso)

- linespace: used to create an array by specifying the range and the number of elements

- random: used to generate random numbers

In [11]:
a = np.zeros((2,3,5))
print('np.zeros((2,3)= \n{}\n'.format(a))

b = np.ones((4,3,4))
print('np.ones((2,3))= \n{}\n'.format(b))

c = np.empty((2,3))
print('np.empty((2,3))= \n{}\n'.format(c))

d = np.arange(1, 2, 0.3)
print('np.arange(1, 2, 0.3)= \n{}\n'.format(d))

d2 = np.arange(1, 4, 0.15)
print('np.arange(1, 4, 0.15)= \n{}\n'.format(d2))

d3 = np.arange(11,20)
print('np.arange(11,20)= \n{}\n'.format(d3))


e = np.linspace(1, 2, 7)
print('np.linspace(1, 2, 7)= \n{}\n'.format(e))

f = np.random.random((2,3))
print('np.random.random((2,3))= \n{}\n'.format(f))

np.zeros((2,3)= 
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]

np.ones((2,3))= 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

np.empty((2,3))= 
[[7.74860419e-304 7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304]]

np.arange(1, 2, 0.3)= 
[1.  1.3 1.6 1.9]

np.arange(1, 4, 0.15)= 
[1.   1.15 1.3  1.45 1.6  1.75 1.9  2.05 2.2  2.35 2.5  2.65 2.8  2.95
 3.1  3.25 3.4  3.55 3.7  3.85]

np.arange(11,20)= 
[11 12 13 14 15 16 17 18 19]

np.linspace(1, 2, 7)= 
[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.        ]

np.random.random((2,3))= 
[[0.0981597  0.79738392 0.05004178]
 [0.6061204  0.29284739 0.14135689]]



# Shape and operation

after we have held some data, we may need to generate some new data structures based on the existing array

- *reshape*: used to generate a new array based on the existing array and the specified shape

- *vstack*: used to stack multiple arrays in vertical direction (the dimensions of the array must be matched) - apilar/amontonar

- *hstack*: used to stack multiple arrays in horizontal direction (the dimensions of the array must be matched)

- *hsplit*: used to split the array horizontally

- *vsplit*: used to split the array vertically


To make it easier to test, let's create a few data:

In [12]:
#an array with a row containing three 0
zero_line = np.zeros((1,3))
#an array with a column containing three 1
one_column = np.ones((3,1))
print("zero_line = \n{}\n".format(zero_line))
print("one_column = \n{}\n".format(one_column))
#a matrix with 2 rows and 3 columns
a = np.array([(1,2,3), (4,5,6)])
#an integer array in the interval of [11,20]
b = np.arange(11, 20)
print("a = \n{}\n".format(a))
print("b = \n{}\n".format(b))

zero_line = 
[[0. 0. 0.]]

one_column = 
[[1.]
 [1.]
 [1.]]

a = 
[[1 2 3]
 [4 5 6]]

b = 
[11 12 13 14 15 16 17 18 19]



In [13]:
b = np.arange(11, 20)
print("b = \n{}\n".format(b))
b = b.reshape(3, -1)
print("b.reshape(3, -1) = \n{}\n".format(b))

b = 
[11 12 13 14 15 16 17 18 19]

b.reshape(3, -1) = 
[[11 12 13]
 [14 15 16]
 [17 18 19]]



The second parameter here is set to -1, which means that it'll be determined based on actual conditions automatically. Since the array has 9 elements originally, the matrix after being resized is 3X3

In [14]:
c = np.vstack((a, b, zero_line))
print("c = np.vstack((a,b, zero_line)) = \n{}\n".format(c))

c = np.vstack((a,b, zero_line)) = 
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]
 [ 0.  0.  0.]]



Similarly, we can also use the hstack for horizontal stacking. This time we need to adjust the structure of the array a first

In [15]:
a = a.reshape(3, 2)
print("a.reshape(3, 2) = \n{}\n".format(a))

d = np.hstack((a, b, one_column))
print("d = np.hstack((a,b, one_column)) = \n{}\n".format(d))

a.reshape(3, 2) = 
[[1 2]
 [3 4]
 [5 6]]

d = np.hstack((a,b, one_column)) = 
[[ 1.  2. 11. 12. 13.  1.]
 [ 3.  4. 14. 15. 16.  1.]
 [ 5.  6. 17. 18. 19.  1.]]



Let's take a look at the split.

First, we split the array d into three arrays in horizontal direction. Then we print out the middle one (the subscript is 1):

In [16]:
d = np.hstack((a, b, one_column))
print("d = np.hstack((a,b, one_column)) = \n{}\n".format(d))
e = np.hsplit(d, 3) # Split a into 3
print("e = np.hsplit(d, 3) = \n{}\n".format(e))
#Then we print out the middle one 
print("e[1] = \n{}\n".format(e[1]))

d = np.hstack((a,b, one_column)) = 
[[ 1.  2. 11. 12. 13.  1.]
 [ 3.  4. 14. 15. 16.  1.]
 [ 5.  6. 17. 18. 19.  1.]]

e = np.hsplit(d, 3) = 
[array([[1., 2.],
       [3., 4.],
       [5., 6.]]), array([[11., 12.],
       [14., 15.],
       [17., 18.]]), array([[13.,  1.],
       [16.,  1.],
       [19.,  1.]])]

e[1] = 
[[11. 12.]
 [14. 15.]
 [17. 18.]]



In addition to specifying number to split the array evenly, we can also specify the number of columns to split. The following is to split the array d from the first column and the third column:

In [17]:
d = np.hstack((a, b, one_column))
print("d = np.hstack((a,b, one_column)) = \n{}\n".format(d))
#Split a after the 1st and the 3rd column
f = np.hsplit(d, (1, 3)) 
print("f = np.hsplit(d, (1, 3)) = \n{}\n".format(f))

d = np.hstack((a,b, one_column)) = 
[[ 1.  2. 11. 12. 13.  1.]
 [ 3.  4. 14. 15. 16.  1.]
 [ 5.  6. 17. 18. 19.  1.]]

f = np.hsplit(d, (1, 3)) = 
[array([[1.],
       [3.],
       [5.]]), array([[ 2., 11.],
       [ 4., 14.],
       [ 6., 17.]]), array([[12., 13.,  1.],
       [15., 16.,  1.],
       [18., 19.,  1.]])]



Finally, we split the array d in the vertical direction. Similarly, if the specified number cannot make the array be split evenly, it will fail:

In [18]:
d = np.hstack((a, b, one_column))
print("d = np.hstack((a,b, one_column)) = \n{}\n".format(d))
g = np.vsplit(d, 3)
print("g = np.vsplit(d, 3) = \n{}\n".format(g))

#h = np.vsplit(d, 2) 
# ValueError: array split does not result in an equal division


d = np.hstack((a,b, one_column)) = 
[[ 1.  2. 11. 12. 13.  1.]
 [ 3.  4. 14. 15. 16.  1.]
 [ 5.  6. 17. 18. 19.  1.]]

g = np.vsplit(d, 3) = 
[array([[ 1.,  2., 11., 12., 13.,  1.]]), array([[ 3.,  4., 14., 15., 16.,  1.]]), array([[ 5.,  6., 17., 18., 19.,  1.]])]



# Index

how to access the data in the NumPy array

for testing convenience, let's create a one-dimensional array first. Its content is integers in the interval of (100,200)

Basically, we can specify the subscripts by array[index] to access the elements of the array.

In [19]:
base_data = np.arange(100, 200)
print("base_data\n={}\n".format(base_data))

print("base_data[10] = {}\n".format(base_data[10]))

base_data
=[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]

base_data[10] = 110



In NumPy, we can create an array containing several subscripts (subíndices) to get the elements in the target array (array objetivo). 
For example:

In [20]:
every_five = np.arange(0, 100, 5)
print("base_data[every_five] = \n{}\n".format(
    base_data[every_five]))

base_data[every_five] = 
[100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]



¡OJO¡

The subscript array (el array de subíndices) can be one-dimensional, or multi-dimensional. 

Let's suppose that we want to get a 2X2 matrix whose content comes from the four subscripts of 1, 2, 10, and 20 in the target array (array objetivo), so the code can be written:

In [21]:
a = np.array([(1,2), (10,20)])
print("a = \n{}\n".format(a))
print("base_data[a] = \n{}\n".format(base_data[a]))

a = 
[[ 1  2]
 [10 20]]

base_data[a] = 
[[101 102]
 [110 120]]



In [22]:
lista_compresion = [x for x in range (0,100) if x%2==0]
lista_compresion

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [23]:
b = np.array(lista_compresion)
len(b)
b = b.reshape(5,-1)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [24]:
base_data = np.arange(100, 200)
print("base_data\n={}\n".format(base_data))
print("b = \n{}\n".format(b))
print("base_data[b] = \n{}\n".format(base_data[b]))

base_data
=[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]

b = 
[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]

base_data[b] = 
[[100 102 104 106 108 110 112 114 116 118]
 [120 122 124 126 128 130 132 134 136 138]
 [140 142 144 146 148 150 152 154 156 158]
 [160 162 164 166 168 170 172 174 176 178]
 [180 182 184 186 188 190 192 194 196 198]]



The above we see is the case where the target array (base_data) is one-dimensional. Let's convert the following array into a 10X10 two-dimensional array.

In [25]:
base_data2 = base_data.reshape(20,-1)
print("base_data2 = np.reshape(base_data, (20, -1)) = \n{}\n".format(base_data2))

base_data2 = np.reshape(base_data, (20, -1)) = 
[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]
 [125 126 127 128 129]
 [130 131 132 133 134]
 [135 136 137 138 139]
 [140 141 142 143 144]
 [145 146 147 148 149]
 [150 151 152 153 154]
 [155 156 157 158 159]
 [160 161 162 163 164]
 [165 166 167 168 169]
 [170 171 172 173 174]
 [175 176 177 178 179]
 [180 181 182 183 184]
 [185 186 187 188 189]
 [190 191 192 193 194]
 [195 196 197 198 199]]



For a two-dimensional array,

- if we only specify one subscript, the result of the access is still an array.

- if we specify two subscripts, the result of the access is the elements inside.

- we can also specify the last element by "-1".

In [26]:
#ahora el array no es de una direccion, sino de dos: (10,10)
print("base_data2[2] = \n{}\n".format(base_data2[2]))
print("base_data2[2, 3] = \n{}\n".format(base_data2[2, 3]))
print("base_data2[-1, -1] = \n{}\n".format(base_data2[-1, -1]))

base_data2[2] = 
[110 111 112 113 114]

base_data2[2, 3] = 
113

base_data2[-1, -1] = 
199



In addition, we can also specify the scope by ":", such as: 2:5 .

-Only to write ":" indicates the full scope. (todo el alcance)

Please see the code below:

It will:

- get all the elements of the row whose subscript is 2
- get all the elements of the column whose subscript is 3
- get all the elements of the rows whose subscripts are in [2,5) and the columns * whose subscripts are in [2,4). Please observe the following output carefully:


In [27]:
base_data2 = base_data.reshape(10, -1)
print("base_data2 = np.reshape(base_data, (10, -1)) = \n{}\n".format(base_data2))
print("base_data2[2, :]] = \n{}\n".format(base_data2[2, :]))
print("base_data2[:, 3]] = \n{}\n".format(base_data2[:, 3]))
print("base_data2[2:5, 2:4]] = \n{}\n".format(base_data2[2:5, 2:4]))

base_data2 = np.reshape(base_data, (10, -1)) = 
[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]

base_data2[2, :]] = 
[120 121 122 123 124 125 126 127 128 129]

base_data2[:, 3]] = 
[103 113 123 133 143 153 163 173 183 193]

base_data2[2:5, 2:4]] = 
[[122 123]
 [132 133]
 [142 143]]



# Mathematics

There are also a lot of mathematical functions in NumPy. Here are some examples.

In [28]:
base_data = (np.random.random((5, 5)) - 0.5) * 100
print("base_data = \n{}\n".format(base_data))

print("np.amin(base_data) = {}".format(np.amin(base_data)))
print("np.amax(base_data) = {}".format(np.amax(base_data)))
print("np.average(base_data) = {}".format(np.average(base_data)))
print("np.sum(base_data) = {}".format(np.sum(base_data)))
print("np.sin(base_data) = \n{}".format(np.sin(base_data)))

base_data = 
[[ 43.19147154 -41.83705626  -0.50109004  33.22681622  47.3219662 ]
 [-45.67220771 -16.4600685   -4.51514834  41.00091247  25.42844511]
 [-18.49985093  18.92907046  -2.40502971 -15.65106091  27.33543635]
 [-28.15542016  22.9354051  -43.47835908  47.36412276  27.44284992]
 [  9.85786346 -48.22009665 -26.21208284 -37.67870755  27.4481111 ]]

np.amin(base_data) = -48.22009664758083
np.amax(base_data) = 47.36412275808376
np.average(base_data) = 1.6878516801683872
np.sum(base_data) = 42.19629200420968
np.sin(base_data) = 
[[-0.71093413  0.83949424 -0.48038185  0.97131578 -0.1967837 ]
 [-0.99291428  0.68317763  0.98061105 -0.15952352  0.29141325]
 [ 0.34262067  0.07943078 -0.67174577 -0.05687165  0.80690739]
 [-0.11863367 -0.81006122  0.4828778  -0.2379289   0.73893205]
 [-0.41967342  0.88948039 -0.8816473   0.02040288  0.73537696]]


In [29]:
arr = np.arange(1,20)
arr = arr * arr              #Multiplies each element by itself 
print("Multpiles: ",arr)
arr = arr - arr              #Subtracts each element from itself
print("Substracts: ",arr)
arr = np.arange(1,20)
arr = arr + arr              #Adds each element to itself
print("Add: ",arr)
arr = arr / arr              #Divides each element by itself
print("Divide: ",arr)
arr = np.arange(1,20)
arr = arr + 50
print("Add +50: ",arr)

Multpiles:  [  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361]
Substracts:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Add:  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
Divide:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Add +50:  [51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [30]:
#Returns the square root of each element 
print("Sqrt: ",np.sqrt(arr))
#Returns the exponentials of each element
print("Exp: ",np.exp(arr))
#Returns the sin of each element
print("Sin: ",np.sin(arr))
#Returns the cosine of each element
print("Cos: ",np.cos(arr))
#Returns the logarithm of each element
print("Log: ",np.log(arr))
#Returns the sum total of elements in the array
print("Sum: ",np.sum(arr))
#Returns the standard deviation of in the array
print("Std: ",np.std(arr))

Sqrt:  [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
 7.54983444 7.61577311 7.68114575 7.74596669 7.81024968 7.87400787
 7.93725393 8.         8.06225775 8.1240384  8.18535277 8.24621125
 8.30662386]
Exp:  [1.40934908e+22 3.83100800e+22 1.04137594e+23 2.83075330e+23
 7.69478527e+23 2.09165950e+24 5.68572000e+24 1.54553894e+25
 4.20121040e+25 1.14200739e+26 3.10429794e+26 8.43835667e+26
 2.29378316e+27 6.23514908e+27 1.69488924e+28 4.60718663e+28
 1.25236317e+29 3.40427605e+29 9.25378173e+29]
Sin:  [ 0.67022918  0.98662759  0.39592515 -0.55878905 -0.99975517 -0.521551
  0.43616476  0.99287265  0.63673801 -0.30481062 -0.96611777 -0.7391807
  0.1673557   0.92002604  0.82682868 -0.02655115 -0.85551998 -0.89792768
 -0.11478481]
Cos:  [ 0.7421542  -0.16299078 -0.91828279 -0.82930983  0.02212676  0.85322011
  0.89986683  0.11918014 -0.77108022 -0.95241298 -0.25810164  0.67350716
  0.98589658  0.39185723 -0.56245385 -0.99964746 -0.5177698   0.44014302
  0.99339038]
Log:  [

# Matrix

let's create a 5X5 random integer matrix. There are two ways to get the transpose of a matrix: 

- .T or transpose function.

In addition, the matrix can be multiplied through the 

- dot function. 

The sample code is as follows:

In [31]:
base_data = np.random.random((5,5))
print("base_data = \n{}".format(base_data))

base_data = 
[[0.1792311  0.72241411 0.75026545 0.58761697 0.81533448]
 [0.78963004 0.79416709 0.1982795  0.619828   0.42741785]
 [0.25544756 0.30392835 0.62716077 0.36237614 0.6284789 ]
 [0.68544701 0.36193351 0.39311833 0.85248706 0.81763532]
 [0.65138303 0.38575173 0.55928875 0.66059205 0.51348216]]


In [32]:
base_data = np.floor((np.random.random((5, 5)) - 0.5) * 100) #quiero que sean numeros enteros
print("base_data = \n{}\n".format(base_data))

print("base_data.T = \n{}\n".format(base_data.T))
print("base_data.transpose() = \n{}\n".format(base_data.transpose()))

matrix_one = np.ones((5, 5))
print("matrix_one = \n{}\n".format(matrix_one))

minus_one = np.dot(matrix_one, -1)
print("minus_one = \n{}\n".format(minus_one))

minus_one2 = np.ones((5,5,))*-1
print("minus_one2 = \n{}\n".format(minus_one2))

#multiplicación de matrices
print("np.dot(base_data, minus_one) = \n{}\n".format(
    np.dot(base_data, minus_one)))

base_data = 
[[-17.  31.  24. -26.  -3.]
 [-36. -18.  41. -42.  37.]
 [  5. -11. -12.  39. -14.]
 [  3. -34. -11.  29.  13.]
 [-15. -24. -31.   4. -34.]]

base_data.T = 
[[-17. -36.   5.   3. -15.]
 [ 31. -18. -11. -34. -24.]
 [ 24.  41. -12. -11. -31.]
 [-26. -42.  39.  29.   4.]
 [ -3.  37. -14.  13. -34.]]

base_data.transpose() = 
[[-17. -36.   5.   3. -15.]
 [ 31. -18. -11. -34. -24.]
 [ 24.  41. -12. -11. -31.]
 [-26. -42.  39.  29.   4.]
 [ -3.  37. -14.  13. -34.]]

matrix_one = 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

minus_one = 
[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]

minus_one2 = 
[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]

np.dot(base_data, minus_one) = 
[[ -9.  -9.  -9.  -9.  -9.]
 [ 18.  18.  18.  18.  18.]
 [ -7.  -7.  -7.  -7.  -7.]
 [  0.   0.   0.   0.   0.]
 [100. 100

# Random Number

Random numbers are a feature we use very often during the programming process, such as generating demo data, or disordering existing data sequence randomly to segment the modeling data and the verification data.

The numpy.random package contains a number of algorithms for random numbers. Here we list the four most common usage:

The four usages are:

- np.random.random: to generate 20 random numbers, each of which is between [0.0, 1.0)
- np.random.rand: to generate a random number based on the specified shape
- np.random.randint: to generate a specified number (such as 20) of random integers - within the specified range (such as [0, 100))
- np.random.permutation: to disorder the sequence of the existing data ([0, 1, 2, ..., 19]) randomly The output is as follows:

In [33]:
print("random: \n{}\n".format(np.random.random(20)));

print("rand: \n{}\n".format(np.random.rand(3, 4, 2)));

print("randint: \n{}\n".format(np.random.randint(0, 100, 20)));

print("permutation: \n{}\n".format(np.random.permutation(np.arange(20))));

random: 
[0.14344886 0.75305416 0.38151749 0.21161089 0.31331131 0.15917274
 0.30011953 0.54378398 0.99028356 0.29873916 0.44987557 0.49264323
 0.96305052 0.68097309 0.68795058 0.75894242 0.15791132 0.85111292
 0.22812132 0.27759274]

rand: 
[[[0.44624157 0.65644572]
  [0.5169891  0.38439453]
  [0.23995798 0.17271334]
  [0.36007927 0.01381958]]

 [[0.82517953 0.40916891]
  [0.18469197 0.50233446]
  [0.55766949 0.96945507]
  [0.84271015 0.23765483]]

 [[0.63985328 0.1388523 ]
  [0.21540815 0.7322794 ]
  [0.82293693 0.06723485]
  [0.62626214 0.29741585]]]

randint: 
[34 10 70 95 56 49 89 10 37 31 19  9 31 31 87 28 21 23 87 42]

permutation: 
[ 8  5 17  0 18 16 11 15  1  3 12  4  2  6 14 19  7 10 13  9]

